FROM amd64/amazoncorretto:17
WORKDIR /app
COPY ./build/libs/hilo-0.0.1-SNAPSHOT.jar /app/hilo.jar
ENTRYPOINT ["java", "-Duser.timezone=Asia/Seoul", "-jar", "-Dspring.profiles.active=dev", "hilo.jar"]
